# C compiler
CC := cc

# Packages
PACKAGES := x11 xrandr xcursor xft fontconfig

# Compiler flags
C_FLAGS := -std=c99 -Iinclude -Iinclude/core \
           -Wall -Wextra -Wpedantic -Wno-format-zero-length \
           $(shell pkg-config --cflags $(PACKAGES))
DEBUG_FLAGS := -DDEBUG -g -fsanitize=address -pg -Werror $(C_FLAGS)

# Libraries
C_LIBRARIES := $(shell pkg-config --libs $(PACKAGES))

# Sandbox parameters
SANDBOX_DISPLAY := :8
SANDBOX := Xephyr $(SANDBOX_DISPLAY)

# Find all source files
SOURCES := $(shell find src -name '*.c')
# Get all corresponding object paths
OBJECTS := $(patsubst src/%.c,build/%.o,$(SOURCES))
# Get all include files
INCLUDES := $(shell find include -name '*.h')

# Get dependencies
DEPENDENCIES := $(patsubst %.o,%.d,$(OBJECTS))

.PHONY: default
default: build

# Include dependencies (.d files) generated by gcc
-include $(DEPENDENCIES)
# Build each object from corresponding source file
build/%.o: src/%.c
	mkdir -p $(dir $@)
	$(CC) $(DEBUG_FLAGS) -c $< -o $@ -MMD

# Build the main executable from all object files
build/fensterchef: $(OBJECTS)
	mkdir -p $(dir $@)
	$(CC) $(DEBUG_FLAGS) $(OBJECTS) -o $@ $(C_LIBRARIES)

# Functions
.PHONY: analyze build sandbox clean

analyze:
	gcc -fanalyzer $(DEBUG_FLAGS) $(SOURCES)

build: build/fensterchef

sandbox: build
	$(SANDBOX) &
	# wait for x server to start
	sleep 1
	DISPLAY=$(SANDBOX_DISPLAY) ./build/fensterchef --verbose --config config
	pkill Xephyr

gdb-sandbox: build
	$(SANDBOX) &
	# wait for x server to start
	sleep 1
	DISPLAY=$(SANDBOX_DISPLAY) gdb -ex run --args ./build/fensterchef --verbose --config config
	pkill Xephyr

clean:
	rm -rf build/

## Tests ##

OBJECTS_WITHOUT_MAIN := $(filter-out build/main.o,$(OBJECTS))
TESTS := $(shell find tests -name '*.c' -and -not -name 'test.c')
TEST_OBJECTS := $(patsubst tests/%.c,tests/%.o,$(TESTS)) tests/test.o
TEST_EXECUTABLES := $(patsubst tests/%.c,tests/%,$(TESTS))
TEST_FLAGS := -Itests $(DEBUG_FLAGS)

# Compile or compile and run tests
.PHONY: tests run-tests

tests: $(TEST_OBJECTS) $(TEST_EXECUTABLES)

run-tests: tests
	for f in $(TEST_EXECUTABLES) ; do ./$$f ; done

tests/%.o: tests/%.c
	$(CC) $(TEST_FLAGS) -c $< -o $@

tests/%: $(OBJECTS_WITHOUT_MAIN) tests/test.o tests/%.o
	$(CC) $(TEST_FLAGS) $^ -o $@ $(C_LIBRARIES)
