.TH FENSTERCHEF 5 "2025-05-11" "Fensterchef" "Fensterchef manual"
.SH NAME
fensterchef - format of fensterchef configuration files
.
.SH DESCRIPTION
The fensterchef configuration file format is very simple and easy to understand.

Settings can be set through simple
.B key value
syntax.  For example:
.B border color
.BR #440088 .
When a line starts with a
.I #
the line is ignored.
Lines can be joined using
.I \\\\
This character must be the first non space character on a line which makes this
line continue the previous line.
It is also possible to run actions like hiding a window.
.
.SH SETTING
.PP
.B auto equalize
.I true
or
.I false
    Make frames equalize their size when splitting/unsplitting.
.PP
.B auto fill void
.I true
or
.I false
    Fill empty frames with stashed frames automatically.
.PP
.B auto remove
.I true
or
.I false
    Remove any frames automatically even if gaps can be filled.
.PP
.B auto remove void
.I true
or
.I false
    Remove empty frames automatically.
.PP
.B auto split
.I true
or
.I false
    When a window is shown, split the current frame to make room to show it.
.PP
.B background
.I color
    Set the background color of fensterchef windows.
.PP
.B border color active
.I color
    Set the border color of active windows.
.PP
.B border color focus
.I color
    Set the border color of focused windows.
.PP
.B border color
.I color
    Set the border color of inactive and not focused windows.
.PP
.B border size
.I number
    Set the size of the border of all windows.
.PP
.B cursor horizontal
.I cursor_name
    Set the cursor shown when resizing horizontally.
.PP
.B cursor moving
.I cursor_name
    Set the cursor shown when moving a window.
.PP
.B cursor root
.I cursor_name
    Set the cursor shown on the root window.
.PP
.B cursor sizing
.I cursor_name
    Set the cursor shown when sizing a corner of a window.
.PP
.B cursor vertical
.I cursor_name
    Set the cursor shown when resizing vertically.
.PP
.B first window number
.I number
    Set the number the first window should receive.
.PP
.B font
.I name
    Set the font used for fensterchef windows.
.PP
.B foreground
.I color
    Set the text color of fensterchef windows.
.PP
.B gaps inner
.IR 1 ,
.I 2
or
.I 4
.IR number s
    Set the gaps between frames and their inner windows.
.PP
.B gaps outer
.IR 1 ,
.I 2
or
.I 4
.IR number s
    Set the gaps between frames and the monitor edges.
.PP
.B modifiers
.I modifiers
    Set the modifiers to apply to all future bindings.
.PP
.B modifiers ignore
.I modifiers
    Set the modifiers to ignore for all bindings.
    For example when setting this to "Shift", then pressing "Shift" will not
    mess with any bindings.
.PP
.B notification duration
.I number
    Set the duration the notification should be visible for.
.PP
.B overlap
.I number
    Set the percentage a window should be counted overlapping a monitor.
    Set this to 100% to only allow this for fullscreen windows.
    Set it to 101% to disable this feature.
.PP
.B text padding
.I number
    The insets of the text in fensterchef windows.
.
.SH ACTION
Actions can be run directly in the configuration file or on a button/key
binding.
Note that the "focused window" can also refer to the pressed window in a button
binding or the window matched in an association.
.PP
.B assign
.I number
    Assign a number to the currently focused frame.
.PP
.B assign window
.I number
    Assign a number to the currently focused window.
.PP
.B center window
    Center the focused window onto the monitor it is on.
.PP
.B center window to
.I pattern
    Center the focused window to the monitor matching the pattern.
    If no monitor matches, nothing happens.
.PP
.B close window
.I number?
    Close the focused window or the window with given number.
.PP
.B dump layout
.I file_name
    Dump all frames and windows to a file.
.PP
.B exchange down
    Exchange the current frame with the frame below it.
.PP
.B exchange left
    Exchange the current frame with the frame left of it.
.PP
.B exchange right
    Exchange the current frame with the frame right of it.
.PP
.B exchange up
    Exchange the current frame with the frame above it.
.PP
.B focus child
.I number?
    Focus the child frame or the ith child frame.
.PP
.B focus down
    Focus the frame below the current frame.
.PP
.B focus
.I number
    Focus the frame with given number.
.PP
.B focus leaf
    Focus the deepest child of the current frame.
    Same as
.B focus child
.BR -1 .
.PP
.B focus left
    Focus the frame on the left of the current frame.
.PP
.B focus parent
.I number?
.PP
.B focus right
    Focus the frame on the right of the current frame.
.PP
.B focus root
.I pattern?
.PP
.B focus up
    Focus the frame on the above the current frame.
.PP
.B focus window
.I number?
    Focus the window with given number.
.PP
.B hint split horizontally
    Hint that the current frame should split horizontally.
.PP
.B hint split vertically
    Hint that the current frame should split vertically.
.PP
.B initiate move
    Initiate a moving of a window with the mouse.
.PP
.B initiate resize
    Initiate a resizing of a window with the mouse.
.PP
.B merge default
    Merge the default configuration with the current configuration.
.PP
.B minimize window
.I number?
    Minimize the focus window or the window with given number.
.PP
.B move down
    Move the current frame down.
.PP
.B move left
    Move the current frame to the left.
.PP
.B move right
    Move the current frame to the right.
.PP
.B move up
    Move the current frame up.
.PP
.B move window by
.I x y
    Move the focused window by given coordinates.
.PP
.B move window to
.I x y
    Move the focused window to given coordinates.
.PP
.B pop stash
    Pop the last stashed frame into the current frame.
.PP
.B quit
    Quit fensterchef.
.PP
.B reload configuration
    Clear the configuration and load all again from the configuration file.
.PP
.B remove
.I number?
    Remove the curent frame or the frame with given number.
.PP
.B resize window by
.I x y
    Resize the focused window by given coordinates.
.PP
.B resize window to
.I x y
    Resize the focused window to given coordinates.
.PP
.B run
.I shell_program
    Run a shell program.
    The shell used is located at `/bin/sh/`.
.PP
.B set floating
    Set the focused window to floating.
.PP
.B set fullscreen
    Set the focused window to fullscreen.
.PP
.B set tiling
    Set the focused window to tiling.
.PP
.B show list
    Show/hide the interactive window list.
.PP
.B show message
.I string
    Show a notification window with given message.
.PP
.B show next window
.I number?
    Show the next window or the ith next window.
.PP
.B show previous window
.I number?
    Show the previous window or the ith previous window.
.PP
.B show run
.I shell_program
    Run a shell program and show its output as notification.
.PP
.B show window
.I number?
    Show the focused window or the window with given number.
.PP
.B split horizontally
    Split the current frame horizontally.
.PP
.B split left horizontally
    Split the current frame horizontally but swap the positions of the split
    frames.
.PP
.B split left vertically
    Split the current frame vertically but swap the positions of the split
    frames.
.PP
.B split vertically
    Split the current frame vertically.
.PP
.B toggle focus
    Toggle the focus from the tiling layer to the floating layer.
.PP
.B toggle fullscreen
    Toggle the mode of a window from
.I X
to fullscreen and vise versa.
.PP
.B toggle tiling
    Toggle the mode of a window from
.I X
to tiling and vise versa.
.
.SH ASSOCIATION
.I STRING ACTIONS

When a line starts with a quoted string like
.I "Navigator,firefox"
then this is the start of an association.
The string refers to the instance name and class name.
You can use
.BR xprop ( 1 )
to click on a window and read off the
.B WM_CLASS
property.

After the string comes the actions that should run when a window with this
instance name and class name is created.
.
.SH BINDING
.I release?
.I transparent?
.IR MODIFIERS + BUTTON | KEY_SYMBOL
.I ACTIONS

This creates a binding that triggers when the specified combination of modifiers
and button/key symbol is pressed/released.

.I transparent
can be used for button bindings to also send the button event to the pressed
window.

.I release
can be used to trigger the bind when releasing the key/button.

.I MODIFIERS
is combined with the currently configured
.I modifiers
setting.
Note that the ignored modifiers can be used to control which additional
physically pressed modifiers should not change the interpretation of a binding.
.
.SH EXAMPLE
.SS Parts of the default configuration
.EX
overlap 80%

auto remove void false
auto fill void true

font Mono

border size 1
border color #000000

gaps inner 0
gaps outer 0

notification duration 2
text padding 6
foreground #000000
background #ffffff

resize tolerance 8

modifiers ignore Lock Mod2
modifiers Mod4

LeftButton initiate resize
MiddleButton minimize window
RightButton initiate move

Shift+r reload configuration
a focus parent
b focus child
Shift+a focus root
q close window
Minus minimize window
n focus next window
p focus previous window
r remove frame
Shift+Space toggle tiling
Space toggle focus
f toggle fullscreen
v split horizontally
s split vertically
k focus up
h focus left
l focus right
j focus down
Shift+k exchange up
Shift+h exchange left
Shift+l exchange right
Shift+j exchange down
w show list
Return run '[ -n "$TERMINAL" ] && "$TERMINAL" || xterm'
.EE
.SS Initial layout
.EX
"1,st-256color" assign window 901, focus window
"2,st-256color" assign window 902, focus window
"3,st-256color" assign window 903, focus window

assign 901

split horizontally
focus right
assign 902

split horizontally
focus right
assign 903

# Use st -n X, this sets the instance name to X
# (a feature of suckless terminal)
run 'st -n 1'
run 'st -n 2'
run 'st -n 3'
.EE
.SS i3-like tiling
.EX
auto split true
auto equalize true
auto fill void true
auto remove true

v hint split horizontally
s hint split vertically

Shift+h move left
Shift+l move right
Shift+k move up
Shift+j move down
.EE
.SS Start ALL windows as floating besides terminal windows
.EX
"st-256color" focus window
"*" set floating, focus window
.EE
.
